# Generated by Django 4.1 on 2024-11-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
